#!/usr/bin/env python

from ROOT import *
import yaml
import sys, os
from array import array

baseWeight = sys.argv[1] ## Baseline weight. this can be overridden by weight definition in the config file
baseCut = sys.argv[2] ## Baseline cut to apply for every steps. "1" not to apply any cut
configFile = sys.argv[3] ## the yaml file which defines cut steps and histograms
dName = sys.argv[4] ## directory name which contains ntuples

config = yaml.load(open(configFile))
steps = config['steps']
hists = config['hists']

ofName = dName.replace('ntuple', 'hist').rstrip('/')+".root"
if os.path.exists(ofName): sys.exit(1)
odName = os.path.dirname(ofName)
if not os.path.exists(odName):
    try: os.makedirs(odName)
    except: pass

chain = TChain("Friends")
chain.Add(dName+"/*.root")
gROOT.SetBatch(True)

if 'NPROOF' in os.environ:
    nProc = os.environ['NPROOF']
    prf = TProof.Open("workers=%s" % nProc)
    chain.SetProof(True)

print "Processing", ofName

oFile = TFile(ofName, 'recreate')

hWeights = {}
for istep, step in enumerate(steps):
    weights = baseWeight.split('*')
    if 'weightsToDrop' in step:
        weights = list(set(weights)-set(step['weightsToDrop']))

    cuts = [baseCut]+step['cuts']
    cut = '&&'.join(['(%s)' % x for x in cuts])

    dout = oFile.mkdir(step['name'])
    dout.cd()

    ## Fill Weight histogram first
    hWeight = TH1D("hWeight", "weight;weight;Events", 100, -2, 2)
    chain.Draw("%s>>hWeight" % ('*'.join(weights)), cut, "goff")
    hWeight.Write()
    hWeights[step['name']] = hWeight

    ## Fill histograms in this step
    if 'hists' not in step: continue
    for hname, hdef in [(x, hists[x]) for x in step['hists'] if x in hists]:
        h = None
        bins = hdef['bins']
        if type(bins) == list:
            if len(bins) == 2 and type(bins[0]) == list:
                h = TH2D('h'+hname, hdef['title'], len(bins[0])-1, array('d', bins[0]),
                                               len(bins[1])-1, array('d', bins[1]))
            else:
                h = TH1D('h'+hname, hdef['title'], len(bins)-1, array('d', bins))
        else:
            if 'nbinsY' in bins:
                h = TH2D('h'+hname, hdef['title'], bins['nbinsX'], bins['xmin'], bins['xmax'],
                                               bins['nbinsY'], bins['ymin'], bins['ymax'])
            else:
                h = TH1D('h'+hname, hdef['title'], bins['nbinsX'], bins['xmin'], bins['xmax'])
        #h.SetDirectory(dout)

        expr = hdef['expr'] if 'expr' in hdef else hname

        weights1 = weights
        if 'weightsToDrop' in hdef:
            weights1 = list(set(weights)-set(hdef['weightsToDrop']))
        weight1 = '*'.join(weights1)

        cuts1 = cuts[:]
        if 'cuts' in hdef:
            cuts1 = list(set(cuts)|set(hdef['cuts']))
        if 'cutsToDrop' in hdef:
            cuts1 = list(set(cuts)-set(hdef['cutsToDrop']))
        cut1 = '&&'.join(['(%s)' % x for x in cuts1])

        chain.Draw("%s>>h%s" % (expr, hname), "%s*(%s)" % (weight1, cut1), "goff")
        #chain.Draw("%s>>%s" % (expr, hname), "1*(%s)" % (weight1), "goff")

        h.Write()
        del h

oFile.cd()
hCutFlow = TH1D("hCutFlow", "Cut flow;;Events", len(steps), 1, len(steps)+1)
hCutFlowNW = TH1D("hCutFlowNW", "Cut flow No Weight;;Events (unweighted)", len(steps), 1, len(steps)+1)
for istep, step in enumerate(steps):
    stepName = step['name']

    hCutFlow.GetXaxis().SetBinLabel(istep+1, stepName)
    hCutFlowNW.GetXaxis().SetBinLabel(istep+1, stepName)

    nEventNW = hWeights[stepName].GetEntries()
    avgW = hWeights[stepName].GetMean()
    hCutFlowNW.SetBinContent(istep+1, nEventNW)
    #hCutFlowNW.SetBinError(istep+1, sqrt(nEventNW))
    hCutFlow.SetBinContent(istep+1, nEventNW*avgW)
    #rmsW = hWeights[step['name']].GetRMS()
    #hCutFlow.SetBinError(istep+1, sqrt(rms*avgW*nEventNW))
hCutFlow.Write()
hCutFlowNW.Write()

oFile.Close()
